### ISSUE TITLE
Try Advent v2

### ISSUE THREAD

**Issue by sashavor** [cc-ai/omnigan#130]
See if it helps improve results

**Comment by vict0rsch** [comment]
@tianyu-z can you share your results / findings / insights and general updates here?

**Comment by tianyu-z** [comment]
It helps but needs a little bit of modification.

#12 AdventV2.1 vs #12 AdventV1 [(https://www.comet.ml/tianyu-z/omnigan/0a10bdb1c39a49d19e3e2135540aac2b/b1bf90d2562b45e2ad97369bf10b48d0/compare?experiment-tab=images&imageId=69c01437ab5c449781faa505eda811d6)
]
Conclusion after eyeballing:
- AdventV2.1 tends to flood less on some of the streetview data
- AdventV2.1 is sensitive to shadows
- AdventV2.1 solved random lines issues
- AdventV2.1 solved sky_ground issues (which is very serious in AdventV2)
- AdventV2.1 solved water_on_the_top_of_cars issues

I think for simple cases, the improvement is significant but it does not perform well on some of the Streetview (complex) cases.
P.S. AdventV2 dropped Sim data for the second stage while AdventV2.1 kept a part of / all of the Sim data.

Example for 1:
![image](https://user-images.githubusercontent.com/53099276/93276624-0b95ba00-f78e-11ea-96ec-51307cdbad96.png)
Example for 2 (left is V2.1 and right is V1):
![image](https://user-images.githubusercontent.com/53099276/93276631-14868b80-f78e-11ea-8fd2-a7d2dc04e0fa.png)
![image](https://user-images.githubusercontent.com/53099276/93276641-18b2a900-f78e-11ea-829e-e27d118a62b2.png)
![image](https://user-images.githubusercontent.com/53099276/93276643-1c463000-f78e-11ea-8fb1-0d5658e19101.png)
Example for 4:
![image](https://user-images.githubusercontent.com/53099276/93276652-249e6b00-f78e-11ea-9663-1b85a9e239d1.png)

More experiments are on the way. I will post them here when they are ready.
****

**Comment by tianyu-z** [comment]
https://github.com/cc-ai/omnigan/pull/137

**Comment by zhangtyu** [comment]
To my surprise, I tried entropy_split = 0.30, 035, 0.40, 0.45, 0.50, 0.55, 0.60, 0.67, 0.75, 0.80, 0.85, 0.90.

The 0.67 one is proposed by the original adventv2 paper. And it turns out to have the best performance.

The train and eval link is here:
https://docs.google.com/spreadsheets/d/1oaXsUeICfhmsbikVOUq0jxLr6th_6j0KpOL2UmmAqpc/edit#gid=0

**Comment by tianyu-z** [comment]
To my surprise, I tried entropy_split = 0.30, 035, 0.40, 0.45, 0.50, 0.55, 0.60, 0.67, 0.75, 0.80, 0.85, 0.90.

The 0.67 one is proposed by the original adventv2 paper. And it turns out to have the best performance.

The train and eval link is here:
https://docs.google.com/spreadsheets/d/1oaXsUeICfhmsbikVOUq0jxLr6th_6j0KpOL2UmmAqpc/edit#gid=0

**Comment by tianyu-z** [comment]
To my surprise, I tried entropy_split = 0.30, 035, 0.40, 0.45, 0.50, 0.55, 0.60, 0.67, 0.75, 0.80, 0.85, 0.90, however the 0.67 one which is proposed by the original adventv2 paper has the best performance.

The train and eval links of these exps are here:
https://docs.google.com/spreadsheets/d/1oaXsUeICfhmsbikVOUq0jxLr6th_6j0KpOL2UmmAqpc/edit#gid=0
