### ISSUE TITLE
Two data loaders for synthetic images

### ISSUE THREAD

**Issue by 51N84D** [cc-ai/omnigan#44]
Currently the code is setup so that there's a separate data loader for synthetic-flooded and synthetic-nonflooded images. As a result, the loaded pairs don't correspond to one another.

Is it worth preserving this structure (and ensuring that the two loaders are shuffling in the same way) or just have one dataloader for the synthetic data?

The fact that we're moving away from "image translation" makes me think the latter is fine. What do you think?

**Comment by 51N84D** [comment]
Maybe the correct answer is whatever is easier to implement/modify haha

**Comment by vict0rsch** [comment]
haha that's a good answer :p 

so I guess I atomized data loaders in order to make things as flexible as possible w.r.t. data presence/absence (r|s, n|f, auxilliary tasks data) etc.

I agree it however does not allow for pairs and that the solution to have one single `sim` dataloader would make mores sense.

I'm not however convinced it would not induce a lot of complexity: a good thing with symmetry is that we can always do for loops etc. and avoid wild `if`s that we might forget and that would break things...

So I'll say this: I'm fine with a single data loader as long as the overall `multi_domain_batch` data structure is the same

**Comment by vict0rsch** [comment]
does that make sense to you @51N84D ?
